"""
models/log_entry.py
───────────────────
Every event generated by the honeypot / attack simulator is stored here.
`severity` and `threat_label` are filled in by the ML engine after classification.
"""

import uuid
import enum
from datetime import datetime
from sqlalchemy import String, DateTime, ForeignKey, Enum as SAEnum, func, Text, Float, Integer
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.dialects.postgresql import UUID

from backend.database import Base


class Severity(str, enum.Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class LogEntry(Base):
    __tablename__ = "log_entries"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    simulation_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("simulations.id"), nullable=False
    )
    timestamp: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), index=True
    )
    source_ip: Mapped[str] = mapped_column(String(45))          # supports IPv6
    dest_ip: Mapped[str] = mapped_column(String(45))
    source_port: Mapped[int] = mapped_column(Integer)
    dest_port: Mapped[int] = mapped_column(Integer)
    protocol: Mapped[str] = mapped_column(String(16))           # TCP | UDP | ICMP
    event_type: Mapped[str] = mapped_column(String(64))         # SSH_LOGIN_ATTEMPT, etc.
    raw_payload: Mapped[str] = mapped_column(Text)
    severity: Mapped[Severity | None] = mapped_column(SAEnum(Severity), nullable=True)
    threat_label: Mapped[str | None] = mapped_column(String(64), nullable=True)
    anomaly_score: Mapped[float | None] = mapped_column(Float, nullable=True)
    is_anomaly: Mapped[bool] = mapped_column(default=False)

    # Relationship
    simulation: Mapped["Simulation"] = relationship(back_populates="logs")
